name: CropCoins
version: 1.1
main: me.dawey.cropcoins.CropCoins
api-version: 1.13
authors: [ DaweY ]
description: CropCoins plugin
softdepend:
  - PlaceholderAPI
commands:
  cropcoins:
    aliases:
      - ccoins
      - cropc
    description: CropCoins main command

permissions:
  cropcoins.give:
    default: op
  cropcoins.take:
    default: op
  cropcoins.set:
    default: op
  cropcoins.reset:
    default: op
  cropcoins.reload:
    default: op
  cropcoins.balance:
    default: op
  cropcoins.balance.others:
    default: op
  cropcoins.send:
    default: op
  cropcoins.top:
    default: op
